### ISSUE TITLE
Numpy cannot find the MKL DLLs

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-feedstock#49] opened 2016-07-21 17:27 UTC
Quote from @ SylvainCorlay in this [comment]( https://github.com/conda-forge/bqplot-feedstock/pull/4#issuecomment-234320891 ).

> @jakirkham @pelson

> @aburgm just told me that the issue comes from the conda-forge package for python itself.

> "Numpy cannot find the MKL DLLs which are in Library/bin. It works without Library/bin in PATH for the Python from the defaults channel but when using Python from conda-forge it needs Library/bin in the PATH. "

Sorry I'm missing some relevant context I think. (though maybe you have told me this before. sorry) What is this in relation to? Did we have some traceback of the error? What dependencies from which channels were in the environment? Based on the path issue, what version of `conda` was involved?

Should add that we don't package NumPy for Windows and have no MKL package. Don't think it is relevant here, but figured it should be mentioned anyways.

Also, am moving this issue to the Python issue tracker.

**Comment by SylvainCorlay** [comment] 2016-07-21 17:30
Yes, this is something I encountered when updating the bqplot feestock

numpy not being imported
 - https://ci.appveyor.com/project/conda-forge/bqplot-feedstock/build/1.0.11

same when pinning an earlier version of numpy
 - https://ci.appveyor.com/project/conda-forge/bqplot-feedstock/build/1.0.13

so there is a dll loading issue in both cases. @aburgm told me that he encountered that issue before and that it only happens when the Python package is the one from conda-forge, and does not happen with the one from the default channel.

**Comment by jakirkham** [comment] 2016-07-22 00:50
@patricksnape @gillins @jjhelmus, could you guys please look into this and see if you can figure anything out?

**Comment by gillins** [comment] 2016-07-22 01:20
Sorry if I am being a bit dense here, but why wouldn't Library/bin be in the PATH?

Windows doesn't have a concept of `rpath` so if a DLL is to be found it must be in the PATH... I suspect the `defaults` Python may be adding certain directories to the PATH maybe?

**Comment by patricksnape** [comment] 2016-07-22 07:56
I'm with @gillins here - either the `defaults` Python has some `post-link` behaviour that adds `Library/bin` to the path or something else is going on.

**Comment by SylvainCorlay** [comment] 2016-07-22 08:36
@patricksnape that is exactly it (for windows only).

**Comment by SylvainCorlay** [comment] 2016-07-22 09:49
I opened a PR on this feedstock checking that numpy is correctly imported and it seems to pass. This is really odd.

**Comment by SylvainCorlay** [comment] 2016-07-22 10:32
oddly things started passing again. The only one that fails now is WIN PY34 x64.

**Comment by SylvainCorlay** [comment] 2016-07-22 10:34
Would you be ok removing the python PY3.4 packages from the conda-forge channel?

**Comment by patricksnape** [comment] 2016-07-22 10:45
From the Anaconda repository the Python 3.4 package doesn't seem to contain any pre or post link scripts - so I don't think any magic is happening there.

**Comment by patricksnape** [comment] 2016-07-22 10:46
Also:

```C:\projects\bqplot-feedstock>"C:\conda\envs\_test\Scripts\jupyter-nbextension.exe" enable widgetsnbextension --py --sys-prefix   1>NUL 2>&1  && if errorlevel 1 exit 1 
C:\projects\bqplot-feedstock>"C:\conda\envs\_test\Scripts\jupyter-nbextension.exe" enable bqplot --py --sys-prefix   && if errorlevel 1 exit 1 
Traceback (most recent call last):
  File "C:\conda\envs\_test\Scripts\jupyter-nbextension-script.py", line 5, in <module>
    sys.exit(notebook.nbextensions.main())
  File "C:\conda\envs\_test\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\conda\envs\_test\lib\site-packages\traitlets\config\application.py", line 596, in launch_instance
    app.start()
  File "C:\conda\envs\_test\lib\site-packages\notebook\nbextensions.py", line 961, in start
    super(NBExtensionApp, self).start()
  File "C:\conda\envs\_test\lib\site-packages\jupyter_core\application.py", line 256, in start
    self.subapp.start()
  File "C:\conda\envs\_test\lib\site-packages\notebook\nbextensions.py", line 869, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\conda\envs\_test\lib\site-packages\notebook\nbextensions.py", line 845, in toggle_nbextension_python
    logger=self.log)
  File "C:\conda\envs\_test\lib\site-packages\notebook\nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "C:\conda\envs\_test\lib\site-packages\notebook\nbextensions.py", line 374, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\conda\envs\_test\lib\site-packages\notebook\nbextensions.py", line 1123, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\conda\envs\_test\lib\site-packages\traitlets\utils\importstring.py", line 41, in import_item
    return __import__(parts[0])
  File "C:\conda\envs\_test\lib\site-packages\bqplot\__init__.py", line 60, in <module>
    from .figure import *
  File "C:\conda\envs\_test\lib\site-packages\bqplot\figure.py", line 33, in <module>
    from .scales import Scale, LinearScale
  File "C:\conda\envs\_test\lib\site-packages\bqplot\scales.py", line 44, in <module>
    import numpy as np
  File "C:\conda\envs\_test\lib\site-packages\numpy\__init__.py", line 180, in <module>
    from . import add_newdocs
  File "C:\conda\envs\_test\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\conda\envs\_test\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\conda\envs\_test\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\conda\envs\_test\lib\site-packages\numpy\core\__init__.py", line 14, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.
```

That isn't numpy not being imported! That is a build error 😄 Looks like numpy is missing a dependency which probably implies a bad numpy build or a bad configuration on Appveyor.

**Comment by SylvainCorlay** [comment] 2016-07-22 12:10
```
import numpy as np
File "C:\conda\envs_test\lib\site-packages\numpy__init__.py", line 180, in 
from . import add_newdocs
File "C:\conda\envs_test\lib\site-packages\numpy\add_newdocs.py", line 13, in 
from numpy.lib import add_newdoc
File "C:\conda\envs_test\lib\site-packages\numpy\lib__init__.py", line 8, in 
from .type_check import *
File "C:\conda\envs_test\lib\site-packages\numpy\lib\type_check.py", line 11, in 
import numpy.core.numeric as nx
File "C:\conda\envs_test\lib\site-packages\numpy\core__init_.py", line 14, in 
from . import multiarray
ImportError: DLL load failed: The specified module could not be found.
```

That looks like numpy not beeing imported because the dll of a submodule cannot be loaded.

**Comment by jjhelmus** [comment] 2016-07-22 13:19
I only have access to the `win-32` platform at the moment and I'm not seeing this issue there so I can't confirm.  I'll try tonight on a `win-64` machine.  

The recipe in anaconda-recipes is applying a [patch](https://github.com/ContinuumIO/anaconda-recipes/blob/master/python-3.5/win-library_bin.patch) which adds \Library\bin to the PATH on startup (at least that what I think it going on) which may be the cause of the issue.  I'll investigate adding this along with the other windows patch in that recipe to the `conda-forge` recipe.

**Comment by jjhelmus** [comment] 2016-07-23 12:25
Tried to replicate this on a `win-64` system but still no luck.  Installing python 3.4 or 3.5 from the `conda-forge` channel and numpy from `defaults` seems to work fine.  I will still be putting in some updates for the python 3.4 and 3.5 recipes to include the patches that are applied in anaconda-recipes but I have no reason to expect these to fix the reported issue.  

@SylvainCorlay are you still seeing this issue?

**Comment by patricksnape** [comment] 2016-07-23 14:36
I was also unable to replicate on my x64 machine.

**Comment by SylvainCorlay** [comment] 2016-07-23 16:31
I eventually skipped the win64+py34 combination for the release. I have no idea why the doll could not be loaded.

**Comment by SylvainCorlay** [comment] 2016-07-25 11:07
I have opened a PR re-enabling the build on `win-64 + py34` to show the issue https://ci.appveyor.com/project/conda-forge/bqplot-feedstock/build/1.0.18

**Comment by patricksnape** [comment] 2016-07-26 08:20
Also, it may have something to do with [this](https://ci.appveyor.com/project/conda-forge/bqplot-feedstock/build/1.0.18/job/7ea54fr55lmsq7d8#L376) which reflects the old conda-build pinning that has now been removed. You may want to try removing that pinning.

**Comment by jjhelmus** [comment] 2016-07-27 14:33
@SylvainCorlay Can you retry the bqplot `win-64 + py34` build.  Some fixes were added to the `conda-forge` Python 3.4 package and I'm curious if they have fixed the issue.

**Comment by jakirkham** [comment] 2016-07-27 14:42
Good point about the pinning, @patricksnape. We should just remove it ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/22 ). 😉

**Comment by SylvainCorlay** [comment] 2016-07-27 15:04
> @SylvainCorlay Can you retry the bqplot win-64 + py34 build. Some fixes were added to the conda-forge Python 3.4 package and I'm curious if they have fixed the issue.

Testing now

**Comment by SylvainCorlay** [comment] 2016-07-27 15:23
@jjhelmus awesome it all works with your Python 3.4 package update!

**Comment by jjhelmus** [comment] 2016-07-27 16:28
Good to hear. I'm going to close this issue, feel free to re-open if you run into the same issue again.

**Closed by jjhelmus** 2016-07-27 16:28 UTC

**Comment by SylvainCorlay** [comment] 2016-07-27 16:41
Thanks again for your help on this.
