### ISSUE TITLE
"Bus Error" with conda-forge python packages

### ISSUE THREAD

**Issue by msarahan** [conda-forge/python-feedstock#108] opened 2017-01-12 15:40 UTC
It seems the conda-forge recipes need to not detect binary files.  This setting changed in conda-build 2.0 from opt-in to opt-out, so this will need to change with the migration to conda-build 2.

https://github.com/conda/constructor/issues/57#issuecomment-272194137

**Comment by ericdill** [comment] 2017-01-12 15:58
@msarahan Does this need a PR against all versions of python we are building?

**Comment by jjhelmus** [comment] 2017-01-12 15:59
I disagree that this option should be turned on, although it would solve the issue.  See my comment in conda/constructor#57

**Comment by ericdill** [comment] 2017-01-12 16:01
@jjhelmus thanks for chiming in on this. It's clear that you have far more experience in this realm than I do.  Ping me if I can do anything to help on this

**Comment by msarahan** [comment] 2017-01-12 16:02
Let's keep the discussion over at the constructor issue for now.  There's more good technical detail there.

**Comment by jjhelmus** [comment] 2017-01-13 15:33
I think conda/constructor#58 should address this issue.  

A similar error might occur if a Python with a binary prefix is updated in the root environment. I do not think this will occur because conda unlinks the "working" Python package prior to installing the new version. Any memory mapped shared libraries should never be rewritten.

**Comment by jjhelmus** [comment] 2017-02-01 01:31
Going to close this issue as I believe this has been fixed in constructor.  Feel free to re-open if this problem still remains.

**Closed by jjhelmus** 2017-02-01 01:31 UTC

**Comment by ericdill** [comment] 2017-02-01 13:37
Thanks for figuring out the root cause of this @jjhelmus and fixing it :smile:
