### ISSUE TITLE
'default.profraw' files appear for python 3.6.10 on MacOS

### ISSUE THREAD

**Issue by Anthchirp** [conda-forge/python-feedstock#339] opened 2020-04-07 10:01 UTC
Issue:
Looks like the 3.6.10 python interpreter is built with profiling support on MacOS. This causes profiling reports (`default.profraw`) to be written to `$cwd` whenever the interpreter is run. Started with the python package built yesterday.

```bash
$ ls
.	..
$ ../bin/python -V
Python 3.6.10
$ ls
.		..		default.profraw
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/wra62962/z:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py36h9f0ad1d_0    conda-forge
libcxx                    9.0.1                         2    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
openssl                   1.1.1f               h0b31af3_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
python                    3.6.10          h4334963_1010_cpython    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                46.1.3           py36h9f0ad1d_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h0b31af3_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : None
       user config file : /Users/wra62962/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.6.10.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/wra62962/bootstrap/conda_base/python.app/Contents  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/wra62962/bootstrap/conda_base/python.app/Contents/pkgs
                          /Users/wra62962/.conda/pkgs
       envs directories : /Users/wra62962/.conda/envs
                          /Users/wra62962/bootstrap/conda_base/python.app/Contents/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.6.10 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 503:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by therc** [comment] 2020-04-07 16:00
#331 might have changed the build environment from 10.13 to 10.14, among other things

**Comment by jjhelmus** [comment] 2020-04-10 20:33
This seems to be new behavior in the `1010` build of Python 3.6.10 build 1009 (which can be installed using `conda install -c conda-forge "python=3.6.10=*1009*" does not produce this file.  

PR #334 produced that build, although I'm not seeing anything obvious there that would cause this behavior.

**Comment by jjhelmus** [comment] 2020-04-10 20:49
The `default.profraw` file is the default profile out file produced when clang is configured to output profiling information via by using an option such as `-fprofile-instr-generate`.  The Python 3.6.10 builds  do have PGO turned on which might be the cause. 

@isuruf Do you have any idea on this?

**Comment by isuruf** [comment] 2020-04-13 23:48
I haven't used clang's pgo options before. Sorry.

**Comment by dopplershift** [comment] 2020-04-21 21:33
This is also happening with Python 3.8.2 build 6.

**Comment by beckermr** [comment] 2020-04-22 14:44
This is causing CI failures. Can we pull the 1010 build until this is fixed?

**Comment by beckermr** [comment] 2020-04-22 14:44
```
SafetyError: The package for python located at /Users/distiller/miniconda3/pkgs/python-3.6.10-h4334963_1010_cpython
appears to be corrupted. The path 'default.profraw'
has an incorrect size.
  reported size: 897352 bytes
  actual size: 908568 bytes
```

**Comment by blink1073** [comment] 2020-04-23 16:13
This is preventing us from releasing any new versions of JupyterLab.

**Comment by blink1073** [comment] 2020-04-23 16:14
Our release script depends on a clean git checkout in the middle of steps, and this file shows up after running various commands.

**Comment by beckermr** [comment] 2020-04-23 16:14
Let's mark this release as broken.

**Comment by isuruf** [comment] 2020-04-23 16:16
I'd hold off on that till someone from @conda-forge/core comments.

**Comment by isuruf** [comment] 2020-04-23 16:16
Sorry, I meant @conda-forge/python

**Comment by beckermr** [comment] 2020-04-23 16:17
kk PR made if we want it: https://github.com/conda-forge/cf-mark-broken/pull/41

**Comment by blink1073** [comment] 2020-04-23 16:17
Note: we are seeing this with `/Users/stslve/miniconda/pkgs/python-3.8.2-hd5f0129_6_cpython`

**Comment by beckermr** [comment] 2020-04-23 16:17
on osx?

**Comment by jjhelmus** [comment] 2020-04-23 16:17
I am in favor of pulling these packages (Python 3.6.10 and 3.8.2 on osx-64).  If someone can investigate the cause further that would be wonderful.

**Comment by blink1073** [comment] 2020-04-23 16:17
Yep

**Comment by beckermr** [comment] 2020-04-23 16:18
I added the py38 one. Noe we wait!

**Comment by blink1073** [comment] 2020-04-23 16:18
Thanks all!

**Comment by blink1073** [comment] 2020-04-23 16:19
Jupyterlab ❤️ :heart: conda-forge.

**Comment by jjhelmus** [comment] 2020-04-23 16:25
Note that pulling these will result in losing the regex change in #334

**Comment by blink1073** [comment] 2020-04-23 16:29
cc @SylvainCorlay  ^^

**Comment by isuruf** [comment] 2020-04-23 16:36
Looks like enabling profile guided optimizations in both the shared library and static library confuses python's Makefile which doesn't separate the profile information from the two builds and is dumped into the same file. This results in a silent failure of building python that use the profile information and the python that generates the profile information is installed instead.

```
2020-04-16T17:46:31.7318120Z warning: code-21659.profclangr: Unsupported instrumentation profile format version
2020-04-16T17:46:31.7319230Z error: No profiles could be merged.
```

**Comment by blink1073** [comment] 2020-04-23 16:38
Nice deep-dive @isuruf!

**Comment by beckermr** [comment] 2020-04-23 16:38
Can we turn it on just for the static lib since that is the one that is actually used in most cases?

**Comment by isuruf** [comment] 2020-04-23 16:39
We could by reverting https://github.com/conda-forge/python-feedstock/pull/338

**Comment by jjhelmus** [comment] 2020-04-23 16:40
#338 is for Python 3.8.2, what about 3.6.10?

**Comment by isuruf** [comment] 2020-04-23 17:18
Hmm, this might be a bug in the clang package

**Comment by isuruf** [comment] 2020-04-23 17:23
> Hmm, this might be a bug in the clang package

Nope, it's the llvm package.

**Comment by blink1073** [comment] 2020-04-24 07:11
I'm also seeing this behavior with `python  3.8.2. hbb7e721_6_cpython conda-forge`.  Manually installing `python==3.8.1` allows us to make JupyterLab releases for now.

**Comment by beckermr** [comment] 2020-04-24 11:24
can you make a PR on cf-mark-broken with the right data? We can merge it and remove the package for now.

**Comment by blink1073** [comment] 2020-04-24 12:35
Done! https://github.com/conda-forge/cf-mark-broken/pull/42

**Comment by jjhelmus** [comment] 2020-04-24 14:06
The `python 3.8.2 hd5f0129_7_cpython` package created in #343 fixes this issue for Python 3.8.  #344 will do the same for 3.6.10 and will close this issue.

**Comment by blink1073** [comment] 2020-04-25 08:26
I haven't seen any issues locally with Python 3.7 environments on OSX.

**Comment by rggjan** [comment] 2020-04-25 09:12
I have the issue on a local build of this feedstock on the Python 3.7 branch. Any idea how to fix this?

**Comment by blink1073** [comment] 2020-04-25 09:17
Run `conda list | grep python` and make a PR similar to https://github.com/conda-forge/cf-mark-broken/pull/42.

**Comment by beckermr** [comment] 2020-04-25 13:08
you cannot mark local builds broken - that repo is for the main conda-forge channels

**Comment by isuruf** [comment] 2020-04-26 18:37
@rggjan, you'll need to rebuild this feedstock locally with the latest build of clang_osx-64=9.0.1 to fix your local build. conda-forge builds are fine now.

**Closed by isuruf** 2020-04-26 18:37 UTC

**Comment by rggjan** [comment] 2020-05-06 06:07
Thanks @isuruf, I think that worked...

**Comment by drorata** [comment] 2020-05-28 11:33
> @rggjan, you'll need to rebuild this feedstock locally with the latest build of clang_osx-64=9.0.1 to fix your local build. conda-forge builds are fine now.

@isuruf Does it mean that the builds currently live are OK? I'm still getting this file generated over and over again...

**Comment by isuruf** [comment] 2020-05-28 14:38
@drorata, please open a different issue.

**Comment by drorata** [comment] 2020-05-29 04:58
@isuruf I tried to reproduce for the new issue and it didn't happen. I'll open a new ticket if needed. Thanks!
